spring:
  application:
    name: hubbo

  datasource:
    url: jdbc:mysql://192.168.56.91/hubbo?characterEncoding=UTF-8&serverTimeZone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root@mysql
    driver-class-name: com.mysql.cj.jdbc.Driver


thread:
  pool:
    core-size: 30
    max-size: 100
    timeout: 100
    time-unit: seconds